server:
  port: 8888
spring:
  application:
    name: weilog
    profiles:
      - dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.86:3306/blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  thymeleaf:
    mode: HTML
logging:
  level:
    root: info
    org.charles.weilog: debug
  file: log/weilog.log