spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.76.44.224:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: blog
    password: blog
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 9999

logging:
  level:
    root: info
    com.lrm: info
  file: log/blog-dev.log



